apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: my-daemonset
spec:
    selector:
      matchLabels:
        app: my-nginix-daemon
    template:
        metadata:
          labels:
            app: my-nginix-daemon
        spec:
            containers:
            - name: my-nginix
              image: nginix
              ports:
              -  containersPort: 80