apiVersion: v1
kind: Service
metadata:
  name: my-clusterIP
  namespace: my-ns

spec:
  type: ClusterIP
  selector:
    matchLabels:
      app: my-app
  ports:
  - name: http
    port: 30002
    targetport: 8080

